2021-03-16-01)

포트 번호
	ORACLE
		1521
	MYSQL
		3306
	SQL SERVER
		1433
/
SELECT '200504' AS 판매년월,
		A.PROD_ID AS 상품번호,
		A.PROD_NAME AS 상품명,
		NVL(B.B_QTY, 0) AS 구매개수,
		NVL(C.C_QTY, 0) AS 판매개수
	FROM PROD A
		LEFT OUTER JOIN (
			SELECT BUY_PROD,
					SUM(BUY_QTY) AS B_QTY
				FROM BUYPROD
				WHERE TO_CHAR(BUY_DATE, 'YYYYMM') = '200504'
				GROUP BY BUY_PROD
		) B ON(A.PROD_ID = B.BUY_PROD)
		LEFT OUTER JOIN (
			SELECT CART_PROD,
					SUM(CART_QTY) AS C_QTY
					FROM CART
					WHERE SUBSTR(CART_NO, 1, 6) = '200504'
					GROUP BY CART_PROD
		) C ON(A.PROD_ID = C.CART_PROD);
/
CREATE OR REPLACE PROCEDURE USP_PROD_INFO(
	P_ID IN VARCHAR2,
	P_DATE IN VARCHAR2,
	V_BUY_QTY OUT NUMBER,
	V_CART_QTY OUT NUMBER
)
IS
BEGIN
SELECT NVL(B.B_QTY, 0),
		NVL(C.C_QTY, 0)
	INTO
		V_BUY_QTY,
		V_CART_QTY
	FROM PROD A
		LEFT OUTER JOIN (
			SELECT BUY_PROD,
					SUM(BUY_QTY) AS B_QTY
				FROM BUYPROD
				WHERE TO_CHAR(BUY_DATE, 'YYYYMM') = P_DATE
				GROUP BY BUY_PROD
		) B ON(A.PROD_ID = B.BUY_PROD)
		LEFT OUTER JOIN (
			SELECT CART_PROD,
					SUM(CART_QTY) AS C_QTY
				FROM CART
				WHERE SUBSTR(CART_NO, 1, 6) = P_DATE
				GROUP BY CART_PROD
		) C ON(A.PROD_ID = C.CART_PROD)
	WHERE A.PROD_ID = P_ID;
END;
/
VAR V_BUY_QTY NUMBER
VAR V_CART_QTY NUMBER
EXECUTE USP_PROD_INFO('P202000001', '200504', :V_BUY_QTY, :V_CART_QTY);
PRINT V_BUY_QTY
PRINT V_CART_QTY;
/






