CREATE TABLE STARGET(
    SURVEY_ID NUMBER,
    ST_MOBILE VARCHAR2(11),
    COMPLETE_YN VARCHAR2(20),
    IN_DATE VARCHAR2(15),
    IN_USER_ID VARCHAR2(20),
    UP_DATE VARCHAR2(15),
    UP_USER_ID VARCHAR2(20),

    CONSTRAINT PK_STARGET PRIMARY KEY(SURVEY_ID, ST_MOBILE)
);

SELECT * FROM STARGET;