2021-03-17-01)
/
-- 사용자 지정 함수
CREATE OR REPLACE FUNCTION TEST_FUNC(P_NAME IN VARCHAR2)
	RETURN VARCHAR2
IS
V_NAME VARCHAR2(100) := '';
BEGIN
	V_NAME := 'MY NAME IS ' || P_NAME;
	RETURN V_NAME;
END;
/
SELECT TEST_FUNC('이학재') FROM DUAL;
/
CREATE OR REPLACE FUNCTION FN_MEMNAME(P_MEM_ID IN VARCHAR2)
	RETURN VARCHAR2
IS
	R_NAME MEMBER.MEM_NAME % TYPE;
BEGIN
	SELECT MEM_NAME
		INTO R_NAME
		FROM MEMBER
		WHERE MEM_ID = P_MEM_ID;
	RETURN R_NAME;
EXCEPTION
	WHEN OTHERS
		THEN
			DBMS_OUTPUT.PUT_LINE('예외 발생 : ' || SQLERRM);
	RETURN NULL;
END;
/
SELECT FN_MEMNAME('a001') FROM DUAL;
/
SET SERVEROUTPUT ON;
/
SELECT CART_NO,
		CART_PROD,
		CART_MEMBER,
		FN_MEMNAME(CART_MEMBER)
	FROM CART
	WHERE CART_NO = '2005040100001';
/
년도 및 상품코드를 입력받으면 해당 년도의 평균 판매 개수를 반환하는 함수
/
CREATE OR REPLACE FUNCTION FN_PRODAVGQTY(
		P_YEAR IN NUMBER,
		P_CODE IN VARCHAR2
	)
	RETURN NUMBER
IS
	R_AVGQTY NUMBER := 0;
BEGIN
	SELECT NVL(ROUND(SUM(CART_QTY) / 12, 2), 0)
		INTO R_AVGQTY
		FROM CART
		WHERE SUBSTR(CART_NO, 1, 4) LIKE P_YEAR
			AND CART_PROD = P_CODE
		GROUP BY CART_PROD;
	RETURN R_AVGQTY;
EXCEPTION
	WHEN OTHERS
		THEN
			RETURN 0;
END;
/
SELECT PROD_ID,
		PROD_NAME,
		FN_PRODAVGQTY(2004, PROD_ID) AS 평균판매개수_2004,
		FN_PRODAVGQTY(2005, PROD_ID) AS 평균판매개수_2005
	FROM PROD;
/