CREATE TABLE SMERGE(
    COL01 VARCHAR(20),
    COL02 VARCHAR(20),
    
    CONSTRAINT PK_SMERGE PRIMARY KEY(COL01)
);

INSERT INTO SMERGE(COL01, COL02) VALUES(1, 1);

COMMIT;

MERGE INTO SMERGE S
    USING CUAL
        ON (S.COL01 = '2')
    WHEN MATCHED THEN
        UPDATE SET S.SCORE = 20
    WHEN NOT MATCHED THEN
        INSERT (S.COURSE_ID, S.STUDENT_ID, S.SCORE)
            VALUES ('C1', 'S1', 20);