SELECT NAME, ANIMAL_INS_TIME
FROM (SELECT A.ANIMAL_ID AS ANIMAL_ID,
             A.NAME      AS NAME,
             A.DATETIME  AS ANIMAL_INS_TIME,
             B.DATETIME  AS ANIMAL_OUTS_TIME
      FROM ANIMAL_INS A
               LEFT OUTER JOIN ANIMAL_OUTS B ON (A.ANIMAL_ID = B.ANIMAL_ID)
      ORDER BY ANIMAL_INS_TIME)
WHERE ANIMAL_OUTS_TIME IS NULL
  AND ROWNUM <= 3;